/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bbque_android_lib_LibBbque */

#ifndef _Included_com_bbque_android_lib_LibBbque
#define _Included_com_bbque_android_lib_LibBbque
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bbque_android_lib_LibBbque
 * Method:    getNumCore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bbque_android_lib_LibBbque_getNumCore
  (JNIEnv *, jclass);

/*
 * Class:     com_bbque_android_lib_LibBbque
 * Method:    getMoreCore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bbque_android_lib_LibBbque_getMoreCore
  (JNIEnv *, jclass);

/*
 * Class:     com_bbque_android_lib_LibBbque
 * Method:    getLessCore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bbque_android_lib_LibBbque_getLessCore
  (JNIEnv *, jclass);

/*
 * Class:     com_bbque_android_lib_LibBbque
 * Method:    freeCore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bbque_android_lib_LibBbque_freeCore
  (JNIEnv *, jclass);

/*
 * Class:     com_bbque_android_lib_LibBbque
 * Method:    sendMessageToApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_bbque_android_lib_LibBbque_sendMessageToApp
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
